export const tokens = {
  colors: {
    background: 'hsl(var(--background))',
    foreground: 'hsl(var(--foreground))',
    card: 'hsl(var(--card))',
    cardForeground: 'hsl(var(--card-foreground))',
    popover: 'hsl(var(--popover))',
    popoverForeground: 'hsl(var(--popover-foreground))',
    primary: 'hsl(var(--primary))',
    primaryForeground: 'hsl(var(--primary-foreground))',
    secondary: 'hsl(var(--secondary))',
    secondaryForeground: 'hsl(var(--secondary-foreground))',
    muted: 'hsl(var(--muted))',
    mutedForeground: 'hsl(var(--muted-foreground))',
    accent: 'hsl(var(--accent))',
    accentForeground: 'hsl(var(--accent-foreground))',
    destructive: 'hsl(var(--destructive))',
    destructiveForeground: 'hsl(var(--destructive-foreground))',
    border: 'hsl(var(--border))',
    input: 'hsl(var(--input))',
    ring: 'hsl(var(--ring))',
    link: 'hsl(var(--link))',
    success: 'hsl(var(--success))',
    successBg: 'hsl(var(--success-bg))',
    successForeground: 'hsl(var(--success-foreground))',
    warning: 'hsl(var(--warning))',
    warningBg: 'hsl(var(--warning-bg))',
    warningForeground: 'hsl(var(--warning-foreground))',
    info: 'hsl(var(--info))',
    infoBg: 'hsl(var(--info-bg))',
    infoForeground: 'hsl(var(--info-foreground))',
    sidebar: {
      background: 'hsl(var(--sidebar-background))',
      foreground: 'hsl(var(--sidebar-foreground))',
      primary: 'hsl(var(--sidebar-primary))',
      primaryForeground: 'hsl(var(--sidebar-primary-foreground))',
      accent: 'hsl(var(--sidebar-accent))',
      accentForeground: 'hsl(var(--sidebar-accent-foreground))',
      border: 'hsl(var(--sidebar-border))',
      ring: 'hsl(var(--sidebar-ring))',
    },
    status: {
      new: { bg: 'hsl(var(--status-new-bg))', text: 'hsl(var(--status-new-text))' },
      contacted: { bg: 'hsl(var(--status-contacted-bg))', text: 'hsl(var(--status-contacted-text))' },
      qualified: { bg: 'hsl(var(--status-qualified-bg))', text: 'hsl(var(--status-qualified-text))' },
      proposalSent: { bg: 'hsl(var(--status-proposal-sent-bg))', text: 'hsl(var(--status-proposal-sent-text))' },
      booked: { bg: 'hsl(var(--status-booked-bg))', text: 'hsl(var(--status-booked-text))' },
      lost: { bg: 'hsl(var(--status-lost-bg))', text: 'hsl(var(--status-lost-text))' },
      completed: { bg: 'hsl(var(--status-completed-bg))', text: 'hsl(var(--status-completed-text))' },
    },
  },
  gradient: {
    primary: 'linear-gradient(135deg, hsl(var(--gradient-primary-start)), hsl(var(--gradient-primary-end)))',
  },
  radius: 'var(--radius)',
}
