// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rifdykpdubrowzbylffe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZmR5a3BkdWJyb3d6YnlsZmZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTc5NDMsImV4cCI6MjA2OTM3Mzk0M30.lhSbTbVWckd9zsT0hRCAO06nPKszZpKNi_sq6-WPmV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Lightweight cache wrapper to reduce repetitive auth.getUser network calls
// Many components call getUser during mount; cache the result briefly to avoid floods.
try {
  // @ts-expect-error augment runtime method
  const originalGetUser = supabase.auth.getUser.bind(supabase.auth);
  let cachedUser: any = null;
  let cachedAt = 0;
  let inflight: Promise<any> | null = null;
  const TTL = 30_000; // 30 seconds

  // @ts-expect-error override runtime method
  supabase.auth.getUser = async () => {
    const now = Date.now();
    if (cachedUser && now - cachedAt < TTL) {
      return { data: { user: cachedUser }, error: null };
    }
    if (inflight) {
      return inflight;
    }
    inflight = originalGetUser().then((res: any) => {
      cachedUser = res?.data?.user ?? null;
      cachedAt = Date.now();
      inflight = null;
      return res;
    }).catch((err: any) => {
      inflight = null;
      return { data: { user: null }, error: err };
    });
    return inflight;
  };
} catch {
  // no-op: if override fails, fall back to default behavior
}
